version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    AWS_DEFAULT_REGION: "ap-south-1"
    ECR_REGISTRY: "390004561073.dkr.ecr.ap-south-1.amazonaws.com"
    AWS_ACCOUNT_ID: "390004561073"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export ECR_LOGIN=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - export ECR_REGISTRY=390004561073.dkr.ecr.ap-south-1.amazonaws.com/dockerfile
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker login --username AWS --password $ECR_LOGIN $ECR_REGISTRY

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t dockerfile .
  post_build:
    commands:
      - echo Build completed on `date`
