version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 |  docker login --username AWS --password-stdin public.ecr.aws/c8s2g4b0
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t dockerfile .
      - docker tag dockerfile:latest public.ecr.aws/c8s2g4b0/dockerfile:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/c8s2g4b0/dockerfile:latest
      - printf '[{"name":"dockerfile","imageUri":"public.ecr.aws/c8s2g4b0/dockerfile:latest"}]' > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
