version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 390004561073.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t dockerfile:latest .
      - echo Pushing the Docker image...
      - docker push 390004561073.dkr.ecr.ap-south-1.amazonaws.com/dockerfile:latest
